server:
  port: 18085
spring:
  application:
    name: search
  profiles:
    active: remote

eureka:
  client:
    service-url:
      defaultZone: http://121.196.101.202:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#超时配置
ribbon:
  ReadTimeout: 300000
  eager-load:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000