server:
  port: 8001

spring:
  application:
    name: gateway-web
  redis:
    host: 121.196.101.202
    port: 6379
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: changgou_goods_route
          #uri: http://localhost:18081
          uri: lb://goods
          predicates:
            #- Host=changgou.com**
            - Path=/api/goods/**
          filters:
          #- PrefixPath=/brand
            - StripPrefix=1
            - name: RequestRateLimiter #请求数限流 名字不能随便写 ，使用默认的facatory
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        #用户微服务
        - id: changgou_user_route
          uri: lb://user
          predicates:
            - Path=/api/user/**,/api/address/**
          filters:
            - StripPrefix=1
            #- PrefixPath=/user

        #订单微服务
        - id: changgou_order_route
          uri: lb://order
          predicates:
            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://121.196.101.202:7001/eureka
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true