server:
  port: 9001
spring:
  application:
    name: user-auth
  redis:
    host: 121.196.101.202
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/changgou_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      max-lifetime: 500000
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://121.196.101.202:7001/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou
  clientSecret: changgou
  cookieDomain: localhost
  cookieMaxAge: -1

jks:
  name: changgou.jks
  storepassword: changgou
  keypassword: changgou
  alias: changgou

#超时配置
ribbon:
  ReadTimeout: 5000
  eager-load:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
